Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using DistroLabCommunity.Models;
using DistroLabCommunity.ViewModel.Community;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DistroLabCommunity.Controllers {

    /// <summary>
    /// Controller for community related actions
    /// </summary>
    [Authorize]
    public class CommunityController : Controller {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IUserHandler _userHandler;
        private readonly IMessageHandler _messageHandler;

        public CommunityController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IUserHandler userHandler, IMessageHandler messageHandler) {
            _userManager = userManager;
            _signInManager = signInManager;
            _userHandler = userHandler;
            _messageHandler = messageHandler;
        }

        /// <summary>
        /// Welcome page for logged in users
        /// Displays:
        ///     -Username
        ///     -Last login time
        ///     -Number of logins the last 30 days
        ///     -Number of unread messages
        /// </summary>
        public IActionResult Welcome() {
            string userId = _userManager.GetUserId(HttpContext.User);
            List<UserLogin> userLogins = _userHandler.GetUserLoginsById(userId);
            List<User> user = _userHandler.GetUserByIdList(userId);
            List<Message> messages = _messageHandler.GetMessagesByReceiverId(userId);
            int unreadMessages = 0;
            foreach (Message m in messages) {
                if (!m.Opened) {
                    unreadMessages++;
                }
            }
            var welcomeViewModel = new WelcomeVM {
                Username = user[0].Username,
                LoginsLast30Days = GetNumberOfLoginsLast30Days(userLogins),
                LastLogin = userLogins[userLogins.Count - 1].Login,
                UnreadMessages = unreadMessages // TODO: Make sure this works
            };
            return View(welcomeViewModel);
        }

        /// <summary>
        /// This action returns a count of how many logins a user has made within the last
        /// 30 days.
        /// </summary>
        /// <param name="Logins"></param>
        /// <returns>int</returns>
        private int GetNumberOfLoginsLast30Days(List<UserLogin> Logins) {
            int n = 0;
            foreach (UserLogin userLogin in Logins) {
                if (userLogin.Login.AddDays(30) >= DateTime.Now) {
                    n++;
                }
            }
            return n;
        }

        /// <summary>
        /// This action fetches all users currently in the Db and returns 
        /// all but the user invoking this action
        /// </summary>
        /// <returns></returns>
        public IActionResult SendMessage() {
            List<User> allUsers = _userHandler.GetAllUsersList();
            List<SendMessageUserVM> allUserVMs = new List<SendMessageUserVM>();
            foreach (User user in allUsers) {
                if (user.UserID != _userManager.GetUserId(HttpContext.User)) {
                    allUserVMs.Add(new SendMessageUserVM {
                        UserID = user.UserID,
                        Username = user.Username
                    });
                }
            }
            SendMessageVM sendMessage = new SendMessageVM {
                Users = allUserVMs
            };
            return View(sendMessage);
        }

        /// <summary>
        /// This action try to create a message with its given parameters.
        /// if receiver exists and if entered title and text has a valid format, the action
        /// try to add it to Db. To get the message Id, the message has to be created and then 
        /// fetched from db. Information about the message is then shown to the sender.
        /// Error messages is created and shown to the user
        /// if some operation neccesary to send the message failed.
        /// </summary>
        /// <param name="receiverName"></param>
        /// <param name="title"></param>
        /// <param name="text"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SendMessage(string receiverName, string title, string text) {
            if (_userHandler.UsernameExists(receiverName)) {
                List<User> resultReceiver = _userHandler.GetUserByUsernameList(receiverName);
                List<User> resultSender = _userHandler.GetUserByIdList(_userManager.GetUserId(HttpContext.User));
                if (resultReceiver.Count == 1 && resultSender.Count == 1) {
                    User receiver = resultReceiver[0];
                    User sender = resultSender[0];
                    if (_messageHandler.AddMessage(title, text, sender, receiver)) {
                        List<Message> messages = _messageHandler.GetMessagesBySenderId(sender.UserID);
                        
                        if (messages.Count > 0) {
                            Message m = messages[0];
                            foreach (Message message in messages) {
                                if(message.TimeStamp > m.TimeStamp) {
                                    m = message;
                                }
                            }
                            TempData["sendMessageStatus"] = "OK";
                            TempData["sendMessageStatusMessage"] = "Message number " + m.MessageID + " sent to " + m.ReceiverUser.Username + " at " + m.TimeStamp + ".";
                        }
                    } else {
                        TempData["sendMessageStatus"] = "ERROR";
                        TempData["sendMessageStatusMessage"] = "Message not sent - All fields has to be set";
                    }
                }
                else {
                    //Unable to fetch sender or receiver from DB
                    TempData["sendMessageStatus"] = "ERROR";
                    TempData["sendMessageStatusMessage"] = "Error - Try again";
                }
            }
            else {
                //User does not exist
                TempData["sendMessageStatus"] = "ERROR";
                TempData["sendMessageStatusMessage"] = "Unable to find user";
            }
            return RedirectToAction("SendMessage");
        }

        /// <summary>
        /// This action will create an InboxVM where receiving user is current user.
        /// </summary>
        /// <returns>InboxVM</returns>
        public IActionResult Inbox() {
            string UserID = _userManager.GetUserId(HttpContext.User);
            List<User> users = _userHandler.GetAllUsersList();
            List<Message> messages = _messageHandler.GetMessagesByReceiverId(UserID);

            List<InboxUserVM> vmUsers = new List<InboxUserVM>();
            foreach (User user in users) {
                if (user.UserID != _userManager.GetUserId(HttpContext.User)) {
                    if (hasMessagesFromUser(user, messages)) {
                        List<InboxMessageVM> vmMessages = new List<InboxMessageVM>();
                        int numberOfUnreadMessagesFromUser = 0;
                        foreach(Message m in messages) {
                            if(m.SenderUser.UserID == user.UserID) {
                                if (!m.Removed) {
                                    if (!m.Opened) {
                                        numberOfUnreadMessagesFromUser++;
                                    }
                                    vmMessages.Add(new InboxMessageVM {
                                        MessageID = m.MessageID,
                                        Sender = m.SenderUser.Username,
                                        TimeStamp = m.TimeStamp,
                                        Title = m.Title,
                                        Opened = m.Opened,
                                        Removed = m.Removed
                                    });
                                }
                            }
                        }
                        vmUsers.Add(new InboxUserVM {
                            Messages = vmMessages,
                            Username = user.Username,
                            TotalNumberOfUnread = numberOfUnreadMessagesFromUser
                        });
                    }
                }
            }

            int numberOfReadMessages = 0;
            int numberOfRemovedMessages = 0;
            foreach (Message message in messages) {
                if (message.Opened) {
                    numberOfReadMessages++;
                }
                if (message.Removed) {
                    numberOfRemovedMessages++;
                }
            }
            
            var inbox = new InboxVM {
                Users = vmUsers,
                TotalNumberOfMessages = messages.Count,
                TotalNumberOfOpened = numberOfReadMessages,
                TotalNumberOfRemoved = numberOfRemovedMessages
            };
            return View(inbox);
        }

        private bool hasMessagesFromUser(User user, List<Message> list) {
            foreach (Message message in list) {
                if (message.SenderUser.Equals(user) && !message.Removed) {
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Fetches a message and returns a viewmodel of that message.
        /// </summary>
        /// <param name="messageId"></param>
        /// <returns>ViewMessageVM</returns>
        public IActionResult ViewMessage(int messageId) {
            if (_messageHandler.SetMessageAsOpened(messageId)) {

Views/Community/Inbox.cshtml
@model DistroLabCommunity.ViewModel.Community.InboxVM

@{
    ViewData["Title"] = "Inbox";
}

<div class="container" style="height: 130px">
    <h1 class="my-4">Inbox</h1>
    <div class="container" style="height: 50px">
        @if (TempData["removedMessageStatus"] != null) {
            <p class="alert alert-danger">@TempData["removedMessageStatus"]</p>
        }
    </div>
    @if (Model.Users.Count == 0) {
        <h4>No messages</h4>
        <div class="col-lg-6">
            <p>Total: </p>
            <p>Opened: </p>
            <p>Removed: </p>
        </div>
        <div class="col-lg-6">
            <p>@Model.TotalNumberOfMessages</p>
            <p>@Model.TotalNumberOfOpened</p>
            <p>@Model.TotalNumberOfRemoved</p>
        </div>
    }
    else {
        <div class="row">
            <div class="col-lg-2">
                <div class="list-group" id="myList" role="tablist">
                    <h4>From</h4>
                    @foreach (var user in Model.Users) {
                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#@user.Username" role="tab">
                            @user.Username
                            @if (user.TotalNumberOfUnread != 0) {
                                <span class="badge badge-light">@user.TotalNumberOfUnread</span>
                            }
                        </a>
                    }
                </div>
                <div class="col-lg-6">
                    <p>Total: </p>
                    <p>Opened: </p>
                    <p>Removed: </p>
                </div>
                <div class="col-lg-6">
                    <p>@Model.TotalNumberOfMessages</p>
                    <p>@Model.TotalNumberOfOpened</p>
                    <p>@Model.TotalNumberOfRemoved</p>
                </div>


            </div>
            <div class="col-lg-8" style="margin-left:50px">
                <div class="tab-content">
                    @foreach (var user in Model.Users) {
                        <div class="tab-pane" id="@user.Username" role="tabpanel">
                            <table class="table table-hover" id="messages_table" style="text-align:justify">
                                <thead>
                                    <tr>
                                        <th style="width: 150px;">Title</th>
                                        <th style="width: 150px">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var message in user.Messages) {
                                        <tr style="cursor: pointer;" onclick="location.href = '@(Url.Action("ViewMessage", "Community" , new { messageId=message.MessageID }))'">
                                            @{
                                                if (!message.Opened) {
                                                    <th style="width: 150px;">@message.Title</th>
                                                }
                                                else {
                                                    <td style="width: 150px;">@message.Title</td>
                                                }
                                            }
                                            <td style="width: 150px;">@message.TimeStamp</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                </div>
            </div>
            <div class="col-lg-2">

            </div>
        </div>
    }

    <script>
        $('#myList a').on('click', function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    </script>

Views/Community/SendMessage.cshtml
@model DistroLabCommunity.ViewModel.Community.SendMessageVM

<div class="container" style="height: 50px; margin: 10px;">
    @{
        if (TempData["sendMessageStatus"] != null) {
            if ((string)TempData["sendMessageStatus"] == "OK") {
                <p class="alert alert-success">@TempData["sendMessageStatusMessage"]</p>
            }
            else {
                <p class="alert alert-danger">@TempData["sendMessageStatusMessage"]</p>
            }
        }
    }
</div>

@using (Html.BeginForm("SendMessage", "Community", FormMethod.Post)) {
<div class="container">
    <div class="form-group">
        <label for="sel1">Recipient:</label>
        <select class="form-control" id="receiverName" name="receiverName" style="max-width: 25%">
            @foreach (var user in Model.Users) {
                <option value="@user.Username">@user.Username</option>
            }
        </select>
    </div>
    <div>
        <label for="username">Title:</label>
        <input type="text" class="form-control" maxlength="55" id="title" name="title" aria-describedby="usernameHelp" placeholder="Enter message title" style="max-width: 40%">
    </div>
    <br>
    <div>
        <label for="username">Message:</label>
        <textarea class="form-control" maxlength="1000" id="text" name="text" aria-describedby="usernameHelp" placeholder="Enter message" style="max-width: 50%; height: 200px; resize:none"></textarea>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Send Message</button>
</div>

    <p>@TempData["sendMessageStatus"]</p>
}

Views/Community/ViewMessage.cshtml
@model DistroLabCommunity.ViewModel.Community.ViewMessageVM

<div class="hero-unit" style="max-width: 800px;">
    <h1>@Model.Title</h1>
    <h4>Sender: @Model.Sender</h4>
    <p><pre>@Model.Text</pre></p>
    @using (Html.BeginForm("RemoveMessage", "Community", FormMethod.Post)) {
        <button type="submit" style="width: 75px" name="messageId" value="@Model.MessageID" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></span></button>
    }
</div>

Views/Community/Welcome.cshtml
@model DistroLabCommunity.ViewModel.Community.WelcomeVM

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <div class="container" style="width: 400px">
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Username
                    <span class="badge badge-primary badge-pill">@Model.Username</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Last login
                    <span class="badge badge-primary badge-pill">@Model.LastLogin</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Logins last 30 days
                    <span class="badge badge-primary badge-pill">@Model.LoginsLast30Days</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Unread Messages
                    <span class="badge badge-primary badge-pill">@Model.UnreadMessages</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-lg-2"></div>
</div>